find_package(PkgConfig)
pkg_check_modules(PC_LIBNL-ROUTE QUIET libnl3)

find_path(LIBNL-ROUTE_INCLUDE_DIR netlink/version.h
	HINTS ${PC_LIBNL-ROUTE_INCLUDEDIR} ${PC_LIBNL_NF_INCLUDE_DIRS} PATH_SUFFIXES libnl3)

find_library(LIBNL-ROUTE_LIBRARY NAMES nl-route-3 nl-route
	HINTS ${PC_LIBNL-ROUTE_LIBDIR} ${PC_LIBNL-ROUTE_LIBRARY_DIRS})

set(LIBNL-ROUTE_LIBRARIES ${LIBNL-ROUTE_LIBRARY})
set(LIBNL-ROUTE_INCLUDE_DIRS ${LIBNL-ROUTE_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(LIBNL-ROUTE DEFAULT_MSG LIBNL-ROUTE_LIBRARY LIBNL-ROUTE_INCLUDE_DIR)

mark_as_advanced(LIBNL-ROUTE_INCLUDE_DIR LIBNL-ROUTE_LIBRARY)

