find_package(PkgConfig)
pkg_check_modules(PC_LIBNL-GENL QUIET libnl3)

find_path(LIBNL-GENL_INCLUDE_DIR netlink/version.h
	HINTS ${PC_LIBNL-GENL_INCLUDEDIR} ${PC_LIBNL_NF_INCLUDE_DIRS} PATH_SUFFIXES libnl3)

find_library(LIBNL-GENL_LIBRARY NAMES nl-genl-3 nl-genl
	HINTS ${PC_LIBNL-GENL_LIBDIR} ${PC_LIBNL-GENL_LIBRARY_DIRS})

set(LIBNL-GENL_LIBRARIES ${LIBNL-GENL_LIBRARY})
set(LIBNL-GENL_INCLUDE_DIRS ${LIBNL-GENL_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(LIBNL-GENL DEFAULT_MSG LIBNL-GENL_LIBRARY LIBNL-GENL_INCLUDE_DIR)

mark_as_advanced(LIBNL-GENL_INCLUDE_DIR LIBNL-GENL_LIBRARY)

